<script type="text/javascript">
    var actionURL = '<?php echo $this->actionUrl; ?>';
    var salt = '<?php echo $this->salt; ?>';
    <?php if( isset($this->modelUri) ){ echo "var graphURI = '".$this->modelUri."';"; }  ?>
    var csvConfigs = [];
    <?php
    if( isset($this->configs) ){
        for($i = 0; $i < count($this->configs); $i++ ){
            echo "csvConfigs[".$i."] = '".wordwrap($this->configs[$i], 1024, "'\n+ '")."';\n";
        };
    }?>
</script>
<?php if( isset($this->scovo) ): ?>
<div><?php echo $this->_('Base URI:') ?><br><input type="text" id="uribase" value="initme" style="width:80%;margin-left:0.6em"></div>

<div><?php echo $this->_('DataStructureDefinition:') ?><br><input type="text" id="datastructure" value="" style="width:80%;margin-left:0.6em"><br><br></div>
<div><?php echo $this->_('DataSet:') ?><br><input type="text" id="dataset" value="" style="width:80%;margin-left:0.6em"><br><br></div>
<div><?php echo $this->_('Measure:') ?><br><input type="text" id="measure" value="" style="width:80%;margin-left:0.6em"><br><br></div>
<div><?php echo $this->_('Attributes:') ?>
<table id="csvimport-attributes">
    <tr>
        <th><?php echo $this->_('Attribute Name') ?></th>
    </tr>
</table>
</div>
<div><?php echo $this->_('Dimensions:') ?>

<table id="csvimport-dimensions">
    <tr>
        <th><?php echo $this->_('Dimension Name') ?></th>
    </tr>
</table>
</div>
<div><?php echo $this->_('Data Range:') ?><br><span id="csvimportDatarange" style="margin-left:0.6em"></span></div>
<?php endif; ?>
<div style="position: relative; overflow: auto; width: 100%; height: 100%;" id="table-holder">
<?php echo $this->table; ?>
</div>
